# Generated by Django 5.0 on 2023-12-28 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0010_productmodel_sell_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('complete', models.BooleanField(default=False, verbose_name='Completed?')),
                ('coupon_code', models.CharField(blank=True, default='None', max_length=200, null=True, verbose_name='Coupon Code')),
                ('coupon_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Coupon Amount')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Transaction Id')),
                ('method', models.CharField(max_length=200, null=True, verbose_name='Method')),
                ('delivery_fee', models.FloatField(blank=True, default=0, null=True, verbose_name='Delivery Fee')),
                ('total', models.FloatField(blank=True, default=0, null=True, verbose_name='Total')),
                ('advance', models.FloatField(blank=True, default=0, null=True, verbose_name='Advance')),
                ('due', models.FloatField(blank=True, default=0, null=True, verbose_name='Due')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('customer_confirmed', 'Customer Confirmed'), ('admin_confirmed', 'Admin Confirmed'), ('in_transit', 'In-Transit'), ('delivered', 'delivered'), ('return', 'Return'), ('cancel', 'Cancel')], default='pending', max_length=200, null=True, verbose_name='Status')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Price')),
                ('total', models.FloatField(blank=True, default=0, null=True, verbose_name='Total')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Size')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='sales.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='product.productmodel', verbose_name='Order Item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ('-created_at',),
            },
        ),
    ]
