# Generated by Django 5.0 on 2023-12-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('customer_confirmed', 'Customer Confirmed'), ('admin_confirmed', 'Admin Confirmed'), ('in_transit', 'In-Transit'), ('delivered', 'Delivered'), ('return', 'Return'), ('cancel', 'Cancel')], default='pending', max_length=200, null=True, verbose_name='Status'),
        ),
    ]
