# Generated by Django 4.2.8 on 2024-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('customer_initial', 'Customer Initial'), ('customer_confirmed', 'Pending'), ('admin_confirmed', 'Confirmed'), ('in_transit', 'In-Transit'), ('delivered', 'Delivered'), ('return', 'Return'), ('cancel', 'Cancel')], default='customer_initial', max_length=200, null=True, verbose_name='Status'),
        ),
    ]
