# Generated by Django 5.0 on 2023-12-26 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categorymodel_options_alter_colormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideosmodel',
            name='video',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'wmv', 'flv'])], verbose_name='Video'),
        ),
    ]
