# Generated by Django 5.0 on 2023-12-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productvideosmodel_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='discount_amount',
            field=models.FloatField(default=0.0, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
