# Generated by Django 5.0 on 2023-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_reviewmodel_reviewimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sell_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sell Count'),
        ),
    ]
