# Generated by Django 4.2.8 on 2023-12-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='product.productmodel', verbose_name='Product'),
        ),
    ]
