# Generated by Django 4.2.8 on 2024-01-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productimagesmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='product.productmodel', verbose_name='Product'),
        ),
    ]
