# Generated by Django 4.2.8 on 2024-01-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productvariantmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideosmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_videos', to='product.productmodel', verbose_name='Product'),
        ),
    ]
