# Generated by Django 4.2.8 on 2024-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvideosmodel_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantmodel',
            options={'ordering': ('created_at',), 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sell_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Sell Count'),
        ),
    ]
