# Generated by Django 5.0 on 2023-12-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_remove_menumodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
