# Generated by Django 4.2.8 on 2023-12-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0004_pagemodel_preferencemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ('-position',), 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.RemoveField(
            model_name='preferencemodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='preferencemodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='preferencemodel',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='preferencemodel',
            name='youtube',
        ),
    ]
