# Generated by Django 4.2.8 on 2024-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0008_toptendingproductsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencemodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
    ]
