# Generated by Django 4.2.8 on 2023-12-29 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('image', models.ImageField(upload_to='campaign/images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('starts_with', models.CharField(blank=True, max_length=30, null=True, verbose_name='Starts with')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaign',
                'ordering': ('-created_at',),
            },
        ),
    ]
