# Generated by Django 4.2.8 on 2023-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_campaignmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmodel',
            name='url_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL path'),
        ),
    ]
